#include "draw.h"
#include "gba.h"

#include "images/garbage.h"
#include "images/start_screen.h"
#include "images/ground_block.h"
#include "images/mario_character.h"
#include "images/prize_block.h"
#include "images/prize_block_popped.h"

#include "images/mario_character_blue.h"
// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    UNUSED(state);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    UNUSED(state);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    UNUSED(state);
}


//This function draws the ground
void drawGround(Ground *ground) {
    for (int i = 0; i < 16; i++) {
        drawImageDMA(130, ground->x + i * 15, 15, 15, ground_block);
        drawImageDMA(145, ground->x + i * 15, 15, 15, ground_block);
    }

}
void drawGroundMarioMovedRight(Ground *ground) {
    ground->x -= 1;
    drawGround(ground);
}

void drawBlockMarioMovedRight(Block *block) {
    block->y -= 1;
    drawBlock(block);
}

void drawGroundMarioMovedLeft(Ground *ground) {
    ground->x += 1;
    drawGround(ground);
}

void drawBlockMarioMovedLeft(Block *block) {
    block->y += 1;
    drawBlock(block);
}

void undrawBlockMarioMovedRight(Block *block) {
    drawRectDMA(block->x, block->y + 15, 1, 15, BACKGROUND);
}

void undrawBlockMarioMovedLeft(Block *block) {
    drawRectDMA(block->x, block->y - 3, 1, 15, BACKGROUND);
}

//This function draws mario on the ground
void drawMario(Mario *mario) {
    drawImageDMA(mario->x, mario->y, mario->width, mario->height, mario_character);

}

void drawMarioMovedRight(Mario *mario) {
    mario->y += 3;
    drawImageDMA(mario->x, mario->y, mario->width, mario->height, mario_character);
}

void undrawMarioMovedRight(Mario *mario) {
    drawRectDMA(mario->x, mario->y - 3, 3, 35, BACKGROUND);
}

void drawMarioMovedLeft(Mario *mario) {
    mario->y -= 3;
    drawImageDMA(mario->x, mario->y, mario->width, mario->height, mario_character);
}

void undrawMarioMovedLeft(Mario *mario) {
    drawRectDMA(mario->x, mario->y + mario->width, 3, 35, BACKGROUND);
}

void undrawMarioMovedUp(Mario *mario) {
    drawRectDMA(mario->x + mario->width, mario->y, 35, 3, BACKGROUND);
}
void undrawMarioMovedDown(Mario *mario) {
    drawRectDMA(mario->x - 3, mario->y, 35, 3, BACKGROUND);
}


void drawMarioJump(Mario *mario, Block *block) {
    for (int i = 0; i < 7; i++) {
        mario->x -= 3;
        drawImageDMA(mario->x, mario->y, mario->width, mario->height, mario_character);
        undrawMarioMovedUp(mario);
        volatile int x = 0;
        for (int i = 0; i < 8000; i++) {
                x++;
        }
    }
    if (block != 0) {
        drawBlockJump(block);
    }
    for (int i = 7; i > 0; i--) {
        mario->x += 3;
        drawImageDMA(mario->x, mario->y, mario->width, mario->height, mario_character);
        undrawMarioMovedDown(mario);

        volatile int x = 0;
        for (int i = 0; i < 8000; i++) {
                x++;
        }
    }
    //drawImageDMA(mario->x, mario->y, mario->width, mario->height, mario_character);

}

void drawBlockJump(Block *block) {
    for (int i = 0; i < 3; i++) {
        block->x -= 3;
        drawImageDMA(block->x, block->y, block->width, block->height, prize_block);
        undrawBlockMovedUp(block);
        volatile int x = 0;
        for (int i = 0; i < 8000; i++) {
                x++;
        }
    }
    for (int i = 3; i > 0; i--) {
        block->x += 3;
        drawImageDMA(block->x, block->y, block->width, block->height, prize_block);
        undrawBlockMovedDown(block);

        volatile int x = 0;
        for (int i = 0; i < 8000; i++) {
                x++;
        }
    }
    drawImageDMA(block->x, block->y, block->width, block->height, prize_block_popped);
    block->isPopped = 1;
    //drawImageDMA(mario->x, mario->y, mario->width, mario->height, mario_character);

}
void undrawBlockMovedUp(Block *block) {

    drawRectDMA(block->x + block->width, block->y, 35, 3, BACKGROUND);
}
void undrawBlockMovedDown(Block *block) {
    drawRectDMA(block->x - 3, block->y, 35, 3, BACKGROUND);
}

void drawBlock(Block *block) {
    if (!block->isPopped) {
        drawImageDMA(block->x, block->y, 15, 15, prize_block);
    } else {
        drawImageDMA(block->x, block->y, 15, 15, prize_block_popped);
    }


}



//TODO : refactor x into y. mario->x becomes mario->y and drawImageDMA(x,y) becomes drawImageDMA(y,x)